src/AdotaPet/AdotaPet/Controllers/AnunciosController.cs
using AdotaPet.Models;
using AdotaPet.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Net.NetworkInformation;
using System.Security.Claims;
namespace AdotaPet.Controllers
{
    [Authorize]
    public class AnunciosController : Controller
    {
        private readonly AppDbContext _context;
        public AnunciosController(AppDbContext context) 
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index() 
        {
            var dados = await _context.Anuncios.Where((anuncio) => anuncio.Status == 0).ToListAsync();

            List<AnuncioInteracaoViewModel> anuncios = [];

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            for (int i = 0; i < dados.Count; i++){
                var temDenuncia = await _context.InteracaoAnuncio.Where((e) => e.UsuarioId.ToString() == idLoggedUser && e.AnuncioId == dados[i].Id && e.InteracaoId == 2).ToListAsync();
                if (temDenuncia.IsNullOrEmpty())
                {
                    var temLike = await _context.InteracaoAnuncio.Where((e) => e.UsuarioId.ToString() == idLoggedUser && e.AnuncioId == dados[i].Id && e.InteracaoId == 1).ToListAsync();

                    AnuncioInteracaoViewModel anuncioCompleto = new AnuncioInteracaoViewModel();

                    anuncioCompleto.Anuncio = dados[i];
                    anuncioCompleto.TemLike = !temLike.IsNullOrEmpty();

                    anuncios.Add(anuncioCompleto);
                }
            }

            return View(anuncios);
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Anuncio anuncio)
        {
            if(ModelState.IsValid) {
                anuncio.Status = StatusAnuncio.Publicado;
                anuncio.DataPostagem = DateTime.Now;

                string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
                Usuario? firstUser = await _context.Usuarios.Where((user)=>user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
                if (firstUser == null)
                {
                    return NotFound();
                }

                anuncio.UsuarioId= firstUser.Id;

                _context.Anuncios.Add(anuncio); 
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(anuncio);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dados = await _context.FindAsync<Anuncio>(id);

            if (dados == null)
            {
                return NotFound();
            }

            return View(dados);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int? id, Anuncio anuncio)
        {
            if (id != anuncio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Anuncios.Update(anuncio);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dados = await _context.FindAsync<Anuncio>(id);

            if (dados == null)
            {
                return NotFound();
            }

            return View(dados);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dados = await _context.FindAsync<Anuncio>(id);

            if (dados == null)
            {
                return NotFound();
            }

            return View(dados);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dados = await _context.FindAsync<Anuncio>(id);

            if (dados == null)
            {
                return NotFound();
            }
            dados.Status = StatusAnuncio.Deletado;
            _context.Anuncios.Update(dados);
            //_context.Anuncios.Remove(dados);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Like(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.FindAsync<Anuncio>(id);
            if (anuncio == null)
            {
                return NotFound();
            }

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
            Usuario? firstUser = await _context.Usuarios.Where((user) => user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
            if (firstUser == null)
            {
                return NotFound();
            }

            var interaction = await _context.InteracaoAnuncio.Where((e)=> e.UsuarioId == firstUser.Id && e.AnuncioId == id && e.InteracaoId == 1).ToListAsync();
            if (!interaction.IsNullOrEmpty())
            {
                _context.InteracaoAnuncio.Remove(interaction.First());
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            InteracaoAnuncio interacaoAnuncio = new InteracaoAnuncio();
            interacaoAnuncio.UsuarioId = firstUser.Id;
            interacaoAnuncio.AnuncioId = anuncio.Id;
            interacaoAnuncio.InteracaoId = 1;

            _context.InteracaoAnuncio.Add(interacaoAnuncio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> Report(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.FindAsync<Anuncio>(id);
            if (anuncio == null)
            {
                return NotFound();
            }

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
            Usuario? firstUser = await _context.Usuarios.Where((user) => user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
            if (firstUser == null)
            {
                return NotFound();
            }

            var interaction = await _context.InteracaoAnuncio.Where((e) => e.UsuarioId == firstUser.Id && e.AnuncioId == id && e.InteracaoId == 2).ToListAsync();
            if (!interaction.IsNullOrEmpty())
            {
                _context.InteracaoAnuncio.Remove(interaction.First());
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            InteracaoAnuncio interacaoAnuncio = new InteracaoAnuncio();
            interacaoAnuncio.UsuarioId = firstUser.Id;
            interacaoAnuncio.AnuncioId = anuncio.Id;
            interacaoAnuncio.InteracaoId = 2;

            _context.InteracaoAnuncio.Add(interacaoAnuncio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

src/AdotaPet/AdotaPet/Controllers/InteracaoAnuncioController.cs
using AdotaPet.Models;
using AdotaPet.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Security.Claims;

namespace AdotaPet.Controllers
{
    [Authorize]
    public class InteracaoAnuncioController : Controller
    {

        private readonly AppDbContext _context;
        public InteracaoAnuncioController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> LikedList()
        {

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
            Usuario? firstUser = await _context.Usuarios.Where((user) => user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
            if (firstUser == null)
            {
                return NotFound();
            }

            //var dados = await _context.Anuncios.Where((anuncio) => anuncio.Status == 0).ToListAsync();
            var dados = await _context.InteracaoAnuncio.Where((interacao) => interacao.UsuarioId == firstUser.Id && interacao.InteracaoId == 1).Include(e => e.Anuncio).ToListAsync();

            List<AnuncioInteracaoViewModel> anuncios = [];

            for (int i = 0; i < dados.Count; i++)
            {
                if (dados[i].Anuncio.Status != StatusAnuncio.Deletado)
                {
                    AnuncioInteracaoViewModel anuncioCompleto = new AnuncioInteracaoViewModel();

                    anuncioCompleto.Anuncio = dados[i].Anuncio;
                    anuncioCompleto.TemLike = true;

                    anuncios.Add(anuncioCompleto);
                }
            }
            return View(anuncios);
        }

        public async Task<ActionResult> Like(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anuncio = await _context.FindAsync<Anuncio>(id);
            if (anuncio == null)
            {
                return NotFound();
            }

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
            Usuario? firstUser = await _context.Usuarios.Where((user) => user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
            if (firstUser == null)
            {
                return NotFound();
            }

            var interaction = await _context.InteracaoAnuncio.Where((e) => e.UsuarioId == firstUser.Id && e.AnuncioId == id && e.InteracaoId == 1).ToListAsync();
            if (!interaction.IsNullOrEmpty())
            {
                _context.InteracaoAnuncio.Remove(interaction.First());
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(LikedList));
            }


            InteracaoAnuncio interacaoAnuncio = new InteracaoAnuncio();
            interacaoAnuncio.UsuarioId = firstUser.Id;
            interacaoAnuncio.AnuncioId = anuncio.Id;
            interacaoAnuncio.InteracaoId = 1;

            _context.InteracaoAnuncio.Add(interacaoAnuncio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(LikedList));
        }


        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> ReportedList()
        {

            string idLoggedUser = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
            Usuario? firstUser = await _context.Usuarios.Where((user) => user.Id.ToString() == idLoggedUser).FirstOrDefaultAsync();
            if (firstUser == null)
            {
                return NotFound();
            }

            //var dados = await _context.Anuncios.Where((anuncio) => anuncio.Status == 0).ToListAsync();
            var dados = await _context.InteracaoAnuncio.Where((interacao) => interacao.InteracaoId == 2).Include(e => e.Anuncio).ToListAsync();

            List<AnuncioInteracaoViewModel> anuncios = [];

            for (int i = 0; i < dados.Count; i++)
            {
                if (dados[i].Anuncio.Status != StatusAnuncio.Deletado){
                AnuncioInteracaoViewModel anuncioCompleto = new AnuncioInteracaoViewModel();

                anuncioCompleto.Anuncio = dados[i].Anuncio;
                    //anuncioCompleto.TemLike = true;

                    anuncios.Add(anuncioCompleto);
                }
            }

            return View(anuncios);
        }

    }

}

src/AdotaPet/AdotaPet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdotaPet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdotaPet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anuncios" asp-action="Index">Anúncios</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="InteracaoAnuncio" asp-action="LikedList">Favoritos</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="InteracaoAnuncio" asp-action="ReportedList">Denunciados</a>
                            </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                                </li>
                        }
                       
                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>

                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                Ola, @User.Identity.Name <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                             <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdotaPet 
            @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>